### ISSUE TITLE
Extra Probe/Gene selection boxes

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/GEO-AWS#18]
From the most recent merged pull request. I understand you have made a change so that there is a centralized probe/gene selection drop-down menu's to be used across all of the analyses but I think there is an artifact in the analyses navbar drop-down menu (depicted below) as they are now individual drop-down options/tabs. I'm not sure if this is intentional or not.

![issue-6-12-15](https://cloud.githubusercontent.com/assets/6685750/8640291/c0ba5578-28c0-11e5-90c9-0649d661a7c3.jpg)

**Comment by gdancik** [comment]
Good catch. Apparently what I did previously didn't completely work, but the latest pull request should fix this.
