### ISSUE TITLE
Gene Symbol

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/GEO-AWS#2]
The current method of finding and match the gene symbol only works if the GEO accession page has a table with the "Gene Symbol" listed. 

We need to test this method on known data sets where this will be an issue.
(Go to GSE654 > Scroll to the bottom of the page > click platform "GPL96" > Scroll to the bottom of the page to the table > Scroll on the table until you see the "Gene Symbol" column header or you don't, indicating the Gene is not provided for that platform)

Ultimately the custom error handlers should work great for this as to not have any red error messages. I will most likely have Henry look into this.

![screenshot 2015-06-08 08 55 33](https://cloud.githubusercontent.com/assets/6685750/8035178/47d290f4-0dbc-11e5-98a7-788150e61adf.png)

**Comment by liaok** [comment]
I am working on it. I got caught up in other things last week. I will commit eveyrthing I have this Friday.

**Comment by jasdumas** [comment]
Great!

**Comment by jasdumas** [comment]
most recent commit fixes this
