### ISSUE TITLE
Error in boxplot(log2(exprInput()))

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/GEO-AWS#6]
Error in boxplot(log2(exprInput())) : 
  error in evaluating the argument 'x' in selecting a method for function 'boxplot': Error in log2(exprInput()) : 
  non-numeric argument to mathematical function

**Comment by gdancik** [comment]
Do you get this error message with GSE13 or another dataset? One possibility is that the log2 function is being applied before the expression data has been retrieved (e.g., log2(NULL) returns the same error message). Therefore, you should only take the log if exprInput() is not NULL.

**Comment by jasdumas** [comment]
Yes, I was using GSE13. I now I have it as:
```
if (input$radio == 1 | input$radio == 2) return (boxplot(log2(exprInput())))
  else return(boxplot(exprInput()))
```

This seems to work now, where numbers 1, 2, 3 correspond to the radio button selections for auto-detect, yes, and no respectively for applying the log2 transformation. I'm gonna work on the auto-detect since at the moment its just a forced log2 just like the "Yes" radio button ! I just tried GSE13507 and it gave a bunch of other errors in the sidebarPanel: 

Here are those errors:
![screenshot 2015-06-18 10 21 23](https://cloud.githubusercontent.com/assets/6685750/8233416/16670cb2-15a4-11e5-8d4c-ba4c6c29f1b8.png)

Here is the GSE13 with "Auto-detect" with log transformation:
![screenshot 2015-06-18 10 28 35](https://cloud.githubusercontent.com/assets/6685750/8233563/ef191e24-15a4-11e5-84ef-d90a3333add8.png)

**Comment by jasdumas** [comment]
I have seen this before when using reactives as inputs to functions like boxplot(), and the x parameter needed to be explicitly set to profiles()

...and the boxplot was moved to its own render function and the if/else/auto-detect statements are contained in the profiles() reactive

`boxplot(x = profiles(), boxwex=0.6, notch=T, main=title, outline=FALSE, las=2, ylab="log2 Expression", col = colors())
`
